/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Html } from "@react-three/drei";

export function PhotoboothSlab(props) {
  const { nodes, materials } = useGLTF("./models/photobooth.glb");
  return (
    <>
      <group {...props} dispose={null} rotation-z={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.002"]}
          position={[-2, 1.4, 1]}
          scale={0.9}
          rotation={[0, Math.PI * 0.5, 0]}
        />

        <mesh rotation={[0, Math.PI * 0.5, 0]} position={[-1.8, 2.1, 1]}>
          <planeGeometry args={[1.5, 2.8, 2]} />
          <meshStandardMaterial color={"black"} />
        </mesh>
      </group>

      <mesh position={[-2.9, 0.2, 1.8]}>
        <boxGeometry args={[1.5, 0.1, 0.1]} />
        <meshStandardMaterial />
      </mesh>

      <mesh position={[-2.9, 0.2, 0.2]}>
        <boxGeometry args={[1.5, 0.1, 0.1]} />
        <meshStandardMaterial />
      </mesh>

      <mesh position={[-3, 0.9, 0.2]} rotation-z={Math.PI * 0.25}>
        <boxGeometry args={[1.9, 0.1, 0.1]} />
        <meshStandardMaterial />
      </mesh>

      <mesh position={[-3, 0.9, 1.8]} rotation-z={Math.PI * 0.25}>
        <boxGeometry args={[1.9, 0.1, 0.1]} />
        <meshStandardMaterial />
      </mesh>

    </>
  );
}


// useGLTF.preload("/photobooth.glb");
